services:
  # user interface
  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    
    depends_on:
      - app-backend

  # api 
  app-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "3001:3001"
    